Task 14 - в процессе
htmlacademy-nodejs/345491-keksobooking pull request #12
Opened 2018-10-18 08:58 UTC by methanol

2018-10-18 15:44 UTC, healqq requested changes

2018-10-18 15:44 UTC, healqq commented on src/hotels/validator.js
> +const ValidateError = require(`../../utils/errors`).ValidateError;
обычно используют прилагательные, типа ValidationError

2018-10-18 15:44 UTC, healqq commented on src/hotels/validator.js
> +  if ((!hotel.offer.title) || (typeof hotel.offer.title !== `string`) || (hotel.offer.title.length < 1) || (hotel.offer.title.length > 140)) {
140 должно быть в константе

2018-10-18 15:44 UTC, healqq commented on src/hotels/hotel-router.js
> +  files[`avatar`][0].path = `${__dirname}/../../static/img/avatars/user01.png`;
тут сервер упадет если пришел запрос без аватара или превью

2018-10-18 15:44 UTC, healqq commented on src/hotels/validator.js
> +  console.log(`>2>>${errors.length}`);
не очень понял что это, в запросе же присылается один объект

2018-10-18 15:44 UTC, healqq commented on src/hotels/validator.js
> +
можно было конечно как-то это покрасивше написать, с циклами какими-нибудь

2018-10-19 09:21 UTC, methanol commented on src/hotels/validator.js
> +const ValidateError = require(`../../utils/errors`).ValidateError;
исправил

2018-10-19 09:21 UTC, methanol commented on src/hotels/validator.js
> +  if ((!hotel.offer.title) || (typeof hotel.offer.title !== `string`) || (hotel.offer.title.length < 1) || (hotel.offer.title.length > 140)) {
исправил

2018-10-19 09:24 UTC, methanol commented on src/hotels/hotel-router.js
> +  files[`avatar`][0].path = `${__dirname}/../../static/img/avatars/user01.png`;
вот тут для меня не совсем понятный момент, как указывать передачу картинок, которые являются необязательными. 
const hotelMedia = upload.fields([{name: `avatar`, maxCount: 1}, {name: `preview`, maxCount: 1}]);

hotelRouter.post(``, parser, hotelMedia, (req, res) => {
В этом коде я правильно их объявил?

2018-10-19 09:26 UTC, methanol commented on src/hotels/validator.js
> +  console.log(`>2>>${errors.length}`);
в запросе приходит массив объектов, в функции validateHotel идет проверка конкретного объекта, а validateHotels прогоняет эту функцию по массиву объектов или проверяет один объект в том редком случае, когда отель в запросе один. подумал, что лучше этот функционал разделить по разным функциям.

2018-10-19 09:30 UTC, methanol commented on src/hotels/validator.js
> +
думал насчет цикла for in, но условия проверки разных полей почти всегда отличаются, поэтому пока оставил как есть. Самое общее условие - это проверка, заполнено ли обязательное поле, это условие можно по циклу прогнать, но код от этого сильно короче не станет.

2018-10-19 21:18 UTC, healqq requested changes

2018-10-19 21:18 UTC, healqq commented on src/hotels/validator.js
> +  return (errors.length > 0) ? errors.join() : hotels;
зачем эта проверка? Если ошибки были - уже вылетело исключение

2018-10-19 21:18 UTC, healqq commented on test/get-hotel.test.js
> +    done;
это что такое?

2018-10-20 07:10 UTC, methanol commented on src/hotels/validator.js
> +  return (errors.length > 0) ? errors.join() : hotels;
убрал эту функцию

2018-10-20 07:11 UTC, methanol commented on test/get-hotel.test.js
> +    done;
попытка разобраться с этой ошибкой:
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/mikhails/Documents/GitHub/345491-keksobooking-node/test/get-hotel.test.js)

2018-10-20 12:39 UTC, healqq requested changes

2018-10-20 12:39 UTC, healqq commented on test/get-hotel.test.js
>      const response = await request(app).
этот тест никуда не годится, нужно отправить все поля с некорректными данными и получить список ошибок для каждого поля, и убедиться что список ошибок правильный

2018-10-20 16:09 UTC, methanol commented on test/get-hotel.test.js
>      const response = await request(app).
исправил

2018-10-20 17:28 UTC, merged