Task 15
htmlacademy-nodejs/345491-keksobooking pull request #13
Opened 2018-10-25 19:19 UTC by methanol

2018-10-28 16:04 UTC, healqq requested changes
Предполагалось что мы не перепишем роутер полностью для тестов, потому что в этом нет никакого смысла, ведь так мы тестируем наш мок, а не настоящий роутер, а что наш роутер будет получать моки сервисов для запуска в тестах, вместо того, чтобы получать реальные сервисы.

2018-10-28 16:04 UTC, healqq commented on src/hotels/hotel-router.js
> +  res.on(`error`, (e) => console.error(e));
это что такое?

2018-10-28 16:04 UTC, healqq commented on src/create-server.js
> +const NOT_FOUND_HANDLER = (req, res) => {
сделать обычными функциями а не константами

2018-10-28 16:04 UTC, healqq commented on src/hotels/hotel-router.js
> +  res.on(`end`, () => res.end());
и это

2018-10-28 17:07 UTC, methanol commented on src/create-server.js
> +const NOT_FOUND_HANDLER = (req, res) => {
вылетело из головы, исправил

2018-10-29 09:13 UTC, healqq requested changes

2018-10-29 09:13 UTC, healqq commented on src/server-task.js
> +    const app = getExpressInstance(hotelRouter);
было бы нагляднее если параметры hotelRouter тоже тут передавались, а не вверху в строке импорта

2018-10-29 09:13 UTC, healqq commented on test/get-hotel.test.js
> +const app = getExpressInstanceMock(hotelRouterMock);
и тут тоже

2018-10-29 09:45 UTC, merged