Task 8
htmlacademy-nodejs/345491-keksobooking pull request #7
Opened 2018-10-03 12:39 UTC by methanol

2018-10-03 14:54 UTC, healqq requested changes
Можно было не создавать каждый раз разный элемент, а создать один, используя конструкцию beforeEach ([документация](https://mochajs.org/))
в целом нет особого смысла так дробить тесты, для всех полей можно было написать один тест, в который засунуть все проверки, дробить стоит когда хотим проверить разные ветки исполнения кода, то есть когда у нас есть всякие условия в тестируемых функциях, например для такой функции: ``` const foo = (a, b) => a > 5 ? a : b; ``` мы захотим написать 2 теста, с a > 5 и меньше 5.

2018-10-03 14:54 UTC, healqq commented on test/generate-entity.test.js
> +const {TITLES, START_PRICE, END_PRICE, TYPES, MIN_ROOM, MAX_ROOM, CHECK, FEATURES, PHOTOS, START_X, START_Y, END_X, END_Y, SEVEN_DAYS} = require(`../src/generate-entity.js`);
а почему generateEntity не тут же, а отдельно импортируется?

2018-10-03 14:54 UTC, healqq commented on test/generate-entity.test.js
> +  it(`array contains element`, function () {
эти строки должны читаться как английские предложения, начиная с it:
```It should contain element```
```It is not empty```
и т.д.

2018-10-03 14:54 UTC, healqq commented on test/generate-entity.test.js
> +    assert.notEqual(((generateEntity().offer.price >= START_PRICE) && (generateEntity().offer.price * END_PRICE < END_PRICE)), true);
что проверяет этот тест?

2018-10-03 14:54 UTC, healqq commented on test/generate-entity.test.js
> +    assert.equal(((generateEntity().offer.rooms >= 0)), true);
что проверяет этот тест

2018-10-03 14:54 UTC, healqq commented on test/generate-entity.test.js
> +  it(`is type of field correct?`, function () {
не хватает проверки что GUESTS находится в рамках

2018-10-03 14:54 UTC, healqq commented on test/generate-entity.test.js
> +    assert.equal(FEATURES.indexOf(generateEntity().offer.features[0]) !== -1, true);
стоит проверить что все элементы есть в массиве FEATURES и что они не повторяются

2018-10-03 14:54 UTC, healqq commented on test/generate-entity.test.js
> +  it(`location is out of range`, function () {
и этот тест

2018-10-03 14:54 UTC, healqq commented on test/generate-entity.test.js
> +  it(`you are not from future`, function () {
эти два можно было объединить в один

2018-10-04 05:46 UTC, methanol commented on test/generate-entity.test.js
> +const {TITLES, START_PRICE, END_PRICE, TYPES, MIN_ROOM, MAX_ROOM, CHECK, FEATURES, PHOTOS, START_X, START_Y, END_X, END_Y, SEVEN_DAYS} = require(`../src/generate-entity.js`);
поставил чтоб не затерялась среди констант, исправил

2018-10-04 05:46 UTC, methanol commented on test/generate-entity.test.js
> +  it(`array contains element`, function () {
исправил

2018-10-04 05:49 UTC, methanol commented on test/generate-entity.test.js
> +    assert.notEqual(((generateEntity().offer.price >= START_PRICE) && (generateEntity().offer.price * END_PRICE < END_PRICE)), true);
предыдущий проверяет что цена в пределах диапазона не вызывает ошибку, а этот проверяет что цена вне пределов этого диапазона вызовет ошибку.

2018-10-04 05:50 UTC, methanol commented on test/generate-entity.test.js
> +    assert.equal(((generateEntity().offer.rooms >= 0)), true);
проверял, что в доме есть хоть одна комната, заменил этот тест на проверку типа данных.

2018-10-04 05:51 UTC, methanol commented on test/generate-entity.test.js
> +  it(`is type of field correct?`, function () {
Добавил. Хотя по заданий количество гостей вообще не ограниченно, что странно.

2018-10-04 05:51 UTC, methanol commented on test/generate-entity.test.js
> +    assert.equal(FEATURES.indexOf(generateEntity().offer.features[0]) !== -1, true);
добавил

2018-10-04 05:54 UTC, methanol commented on test/generate-entity.test.js
> +  it(`location is out of range`, function () {
проверяет случай когда координаты выходят за установленные границы. первые два условия убрал, они не нужны.

2018-10-04 05:54 UTC, methanol commented on test/generate-entity.test.js
> +  it(`you are not from future`, function () {
объединил

2018-10-04 08:30 UTC, healqq requested changes
В половине тестов остался вызов generateEntity()

2018-10-04 08:30 UTC, healqq commented on test/generate-entity.test.js
> +      for (let i = 0; i < testingEntity.offer.features.length; i++) {
у массива есть метод [array.every](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/every), он тут хорошо смотрелся бы

2018-10-04 08:30 UTC, healqq commented on test/generate-entity.test.js
> +      for (let i = 0; i < testingEntity.offer.features.length; i++) {
тут можно следовать такой логике: индекс каждого элемента должен соответствовать индексу первого такого элемента в массиве (array.indexOf)

2018-10-04 08:32 UTC, healqq commented on test/generate-entity.test.js
> +  it(`location is out of range`, function () {
этот тест ничего не проверяет, потому что мы проверяем не объект, а то что мы сами с объектом сделали (умножили какое-то поле на какое-то число)

2018-10-04 08:34 UTC, healqq commented on test/generate-entity.test.js
> +    assert.notEqual(((generateEntity().offer.price >= START_PRICE) && (generateEntity().offer.price * END_PRICE < END_PRICE)), true);
Этот тест ничего не проверяет, мы тестируем не полученный объект, а что-то что мы сами и изменили, с таким же успехом можно было написать ```assert.notEqual(((END_PRICE + 1 >= START_PRICE) && (END_PRICE + 1 < END_PRICE)), true);```

2018-10-04 10:41 UTC, methanol commented on test/generate-entity.test.js
> +      for (let i = 0; i < testingEntity.offer.features.length; i++) {
заменил на этот метод

2018-10-04 10:44 UTC, methanol commented on test/generate-entity.test.js
> +      for (let i = 0; i < testingEntity.offer.features.length; i++) {
я не совсем понял, что ты имеешь в виду. по моей логике сравнивается index и  lastIndex каждого элемента, и если они равны - значит такой элемент один и повторов в массиве нет.

2018-10-04 11:52 UTC, merged