Task 9 - в процессе
htmlacademy-nodejs/345491-keksobooking pull request #8
Opened 2018-10-05 11:10 UTC by methanol

задание в процессе выполнения

2018-10-06 11:18 UTC, healqq requested changes

2018-10-06 11:18 UTC, healqq commented on src/welcome-task.js
> +const readline = require(`readline`);
все require должны идти в начале модуля

2018-10-06 11:18 UTC, healqq commented on src/welcome-task.js
> +                case `yes`:
в константы

2018-10-06 11:18 UTC, healqq commented on src/welcome-task.js
> +              homes = JSON.stringify(generateElements(count));
зачем генерить данные на этом шаге? вдруг нам дадут плохой путь и мы выйдем, получается лишняя работа

2018-10-06 11:18 UTC, healqq commented on src/welcome-task.js
> +        if (err1) {
эта функция очень  запутанная, стоит сначала узнать, нужно ли что-то делать, а потом выполнить операцию по записи в файл, если это требуется, это будет намного более читабельно

2018-10-06 11:18 UTC, healqq commented on src/welcome-task.js
> +            if (count >= 1) {
стоит использовать приведение типа

2018-10-06 11:18 UTC, healqq commented on src/welcome-task.js
> +                  fs.writeFile(`${process.cwd()}/${way}/data.json`, homes, (errHandler, closeDialog));
конструкция (errHandler, closeDialog) возвращает closeDialog, я подозреваю что это не то, что ты хотел получить

2018-10-06 11:18 UTC, healqq commented on src/welcome-task.js
> +        fs.writeFile(`${process.cwd()}/${way}/data.json`, homes, (errHandler, closeDialog));
конструкция (errHandler, closeDialog) возвращает closeDialog, я подозреваю что это не то, что ты хотел получить

2018-10-06 13:35 UTC, methanol commented on src/welcome-task.js
> +const readline = require(`readline`);
исправил

2018-10-06 13:35 UTC, methanol commented on src/welcome-task.js
> +                case `yes`:
исправил

2018-10-06 13:35 UTC, methanol commented on src/welcome-task.js
> +              homes = JSON.stringify(generateElements(count));
перенес

2018-10-06 13:35 UTC, methanol commented on src/welcome-task.js
> +            if (count >= 1) {
преобразовал к числу

2018-10-06 13:37 UTC, methanol commented on src/welcome-task.js
> +                  fs.writeFile(`${process.cwd()}/${way}/data.json`, homes, (errHandler, closeDialog));
да в общем мне надо было добавить закрытие после записи данных, так что это мне вроде и надо было.

2018-10-06 14:22 UTC, healqq requested changes

2018-10-06 14:22 UTC, healqq commented on src/welcome-task.js
> +let homes = [];
теперь можно не объявлять переменную глобально

2018-10-06 14:22 UTC, healqq commented on src/welcome-task.js
> +const POSITIVE = `yes`;
я бы завел enum для ответов

2018-10-06 14:33 UTC, methanol commented on src/welcome-task.js
> +let homes = [];
исправил

2018-10-06 14:33 UTC, methanol commented on src/welcome-task.js
> +const POSITIVE = `yes`;
исправил

2018-10-07 13:27 UTC, healqq requested changes

2018-10-07 13:27 UTC, healqq commented on test/welcome-task.test.js
> +  it(`contains rigth data`, function (done) {
right

2018-10-07 13:27 UTC, healqq commented on test/welcome-task.test.js
> +    let arrLength = 0;
зачем эта переменая тут объявляется?

2018-10-07 13:27 UTC, healqq commented on test/welcome-task.test.js
> +          return;
здесь можно вызвать assert.fail чтобы тест зафейлить, вместо того, что ты делаешь с testFunc

2018-10-07 14:05 UTC, methanol commented on test/welcome-task.test.js
> +          return;
убрал testFunc. заменил на assert.equal(!!err, false);

2018-10-08 07:14 UTC, merged